version: '3.8'

services:
  lean-engine:
    image: quantconnect/lean:latest
    container_name: lean-backtest
    volumes:
      - ./Lean/Algorithm.Python:/Lean/Algorithm.Python
      - ./Lean/Data:/Lean/Data
      - ./Lean/Results:/Results
      - ./config.json:/Lean/config.json
    working_dir: /Lean
    command: dotnet QuantConnect.Lean.Launcher.dll
    environment:
      - LEAN_CONFIG_FILE=/Lean/config.json
    networks:
      - lean-network

networks:
  lean-network:
    driver: bridge